# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-16 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('title', 'location', 'price')},
        ),
        migrations.AddField(
            model_name='listing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
