# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 12:19
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20160425_2018'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='listing',
            options={'ordering': ('title', 'location', 'description', 'price', 'picture')},
        ),
        migrations.AddField(
            model_name='listing',
            name='approved',
            field=models.BooleanField(default='false'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='get_slug_name', unique_with=('pub_date',)),
        ),
    ]
