# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_auto_20160427_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='approved',
        ),
        migrations.AddField(
            model_name='listing',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
