# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surf_level',
            field=models.IntegerField(choices=[(1, 'Beginner'), (2, 'Intermediate'), (3, 'Advanced'), (4, 'PRO Surfer')], default=1),
        ),
    ]
