# Twitter
SOCIAL_AUTH_TWITTER_KEY = 'BAAu89kmTK2zgzv2Atkg2xKhF'
SOCIAL_AUTH_TWITTER_SECRET = 'Lx1ttUFO0BlqacuNBaHU6EuxyN4xD9HbLg6SiCwPeWSp4XzHVT'

SOCIAL_AUTH_LOGIN_REDIRECT_URL = '/home/'
SOCIAL_AUTH_LOGIN_URL = '/'